/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface EntropyMissingAllowThisInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "add"
      | "addWithEntropyCorrect"
      | "addWithEntropyWrong"
      | "confidentialProtocolId"
      | "entropyOracle"
      | "entropyRequests"
      | "getEntropyOracle"
      | "initializeCorrect"
      | "initializeWrong"
      | "requestEntropy"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "EntropyRequested"): EventFragment;

  encodeFunctionData(functionFragment: "add", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "addWithEntropyCorrect",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "addWithEntropyWrong",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "confidentialProtocolId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "entropyOracle",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "entropyRequests",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getEntropyOracle",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "initializeCorrect",
    values: [BytesLike, BytesLike, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "initializeWrong",
    values: [BytesLike, BytesLike, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "requestEntropy",
    values: [BytesLike]
  ): string;

  decodeFunctionResult(functionFragment: "add", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "addWithEntropyCorrect",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "addWithEntropyWrong",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "confidentialProtocolId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "entropyOracle",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "entropyRequests",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getEntropyOracle",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "initializeCorrect",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "initializeWrong",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "requestEntropy",
    data: BytesLike
  ): Result;
}

export namespace EntropyRequestedEvent {
  export type InputTuple = [requestId: BigNumberish, caller: AddressLike];
  export type OutputTuple = [requestId: bigint, caller: string];
  export interface OutputObject {
    requestId: bigint;
    caller: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface EntropyMissingAllowThis extends BaseContract {
  connect(runner?: ContractRunner | null): EntropyMissingAllowThis;
  waitForDeployment(): Promise<this>;

  interface: EntropyMissingAllowThisInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  add: TypedContractMethod<[], [string], "nonpayable">;

  addWithEntropyCorrect: TypedContractMethod<
    [requestId: BigNumberish],
    [string],
    "nonpayable"
  >;

  addWithEntropyWrong: TypedContractMethod<
    [requestId: BigNumberish],
    [string],
    "nonpayable"
  >;

  confidentialProtocolId: TypedContractMethod<[], [bigint], "view">;

  entropyOracle: TypedContractMethod<[], [string], "view">;

  entropyRequests: TypedContractMethod<[arg0: BigNumberish], [boolean], "view">;

  getEntropyOracle: TypedContractMethod<[], [string], "view">;

  initializeCorrect: TypedContractMethod<
    [
      encryptedInput1: BytesLike,
      encryptedInput2: BytesLike,
      inputProof1: BytesLike,
      inputProof2: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  initializeWrong: TypedContractMethod<
    [
      encryptedInput1: BytesLike,
      encryptedInput2: BytesLike,
      inputProof1: BytesLike,
      inputProof2: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  requestEntropy: TypedContractMethod<[tag: BytesLike], [bigint], "payable">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "add"
  ): TypedContractMethod<[], [string], "nonpayable">;
  getFunction(
    nameOrSignature: "addWithEntropyCorrect"
  ): TypedContractMethod<[requestId: BigNumberish], [string], "nonpayable">;
  getFunction(
    nameOrSignature: "addWithEntropyWrong"
  ): TypedContractMethod<[requestId: BigNumberish], [string], "nonpayable">;
  getFunction(
    nameOrSignature: "confidentialProtocolId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "entropyOracle"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "entropyRequests"
  ): TypedContractMethod<[arg0: BigNumberish], [boolean], "view">;
  getFunction(
    nameOrSignature: "getEntropyOracle"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "initializeCorrect"
  ): TypedContractMethod<
    [
      encryptedInput1: BytesLike,
      encryptedInput2: BytesLike,
      inputProof1: BytesLike,
      inputProof2: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "initializeWrong"
  ): TypedContractMethod<
    [
      encryptedInput1: BytesLike,
      encryptedInput2: BytesLike,
      inputProof1: BytesLike,
      inputProof2: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "requestEntropy"
  ): TypedContractMethod<[tag: BytesLike], [bigint], "payable">;

  getEvent(
    key: "EntropyRequested"
  ): TypedContractEvent<
    EntropyRequestedEvent.InputTuple,
    EntropyRequestedEvent.OutputTuple,
    EntropyRequestedEvent.OutputObject
  >;

  filters: {
    "EntropyRequested(uint256,address)": TypedContractEvent<
      EntropyRequestedEvent.InputTuple,
      EntropyRequestedEvent.OutputTuple,
      EntropyRequestedEvent.OutputObject
    >;
    EntropyRequested: TypedContractEvent<
      EntropyRequestedEvent.InputTuple,
      EntropyRequestedEvent.OutputTuple,
      EntropyRequestedEvent.OutputObject
    >;
  };
}
